### ISSUE TITLE
登录佳明获取活动似乎失败了

### ISSUE THREAD

**Issue by MadYGY** [XiaoSiHwang/garmin-sync-coros#10]
我打印了一下获取到的佳明活动数量, 返回结果为0, 两天前还正常,
    all_activities = garminClient.getAllActivities()
    logger.warning(f"Garmin activity count: {len(all_activities)}")

**Comment by MadYGY** [comment]
![image](https://github.com/user-attachments/assets/0dbcfe68-7f03-4c80-93d9-bdb7199c6e3e)

**Comment by MadYGY** [comment]
收到, 感谢

**Comment by XiaoSiHwang** [comment]
先不用关Issue哈哈哈，我修复完手动关，这次刚好赶上佳明、高驰两步接口都更新所以就报这些bug

**Comment by XiaoSiHwang** [comment]
已修复问题
