### ISSUE TITLE
高驰上传似乎没有成功

### ISSUE THREAD

**Issue by MadYGY** [XiaoSiHwang/garmin-sync-coros#14]
![image](https://github.com/user-attachments/assets/486b669e-ea1f-4285-86a4-dc7446d18690)

**Comment by MadYGY** [comment]
奇怪的是12.8日同步成功了
![image](https://github.com/user-attachments/assets/d2a2867f-d722-40ba-bee3-1514d349081d)

**Comment by MadYGY** [comment]
尝试过手动删除数据库中的437560105这条记录, 再手动运行一遍, 高驰中还是没有显示这条记录

**Comment by woshicby** [comment]
老版本吧，高驰上传接口变了

**Comment by MadYGY** [comment]
> 老版本吧，高驰上传接口变了

新版本, 重新fork了的

**Comment by XiaoSiHwang** [comment]
已解决！！
