### ISSUE TITLE
部份garmin跑步記錄同步到CORSO後變成跑步机記錄

### ISSUE THREAD

**Issue by zaurus1229** [XiaoSiHwang/garmin-sync-coros#3]
部份garmin跑步記錄同步到CORSO後變成跑步机記錄, 同時沒有任何LAP資料

**Comment by XiaoSiHwang** [comment]
您好，这个问题是佳明升级版本后导致高驰对佳明跑步fit会自动转换成跑步机模式问题😂😂😂😂目前无法解决只能由高驰修复
