### ISSUE TITLE
同步失败

### ISSUE THREAD

**Issue by Para-line** [XiaoSiHwang/garmin-sync-coros#6]
actions没有报错，但是高驰中看不到数据

**Comment by XiaoSiHwang** [comment]
> actions没有报错，但是高驰中看不到数据

我看你的执行好像没啥问题，数据库也同步进去了，你是中途开了高驰的网页吗？

**Comment by Para-line** [comment]
> > actions没有报错，但是高驰中看不到数据
> 
> 我看你的执行好像没啥问题，数据库也同步进去了，你是中途开了高驰的网页吗？

哦哦，我最后发现是第一次没有同步成功，但是数据库里应该是把这些记录标记为已经同步过，然后之后同步的时候就直接跳过了，感谢你的回复

**Comment by XiaoSiHwang** [comment]
> > > actions没有报错，但是高驰中看不到数据
> 
> > 
> 
> > 我看你的执行好像没啥问题，数据库也同步进去了，你是中途开了高驰的网页吗？
> 
> 
> 
> 哦哦，我最后发现是第一次没有同步成功，但是数据库里应该是把这些记录标记为已经同步过，然后之后同步的时候就直接跳过了，感谢你的回复

😂好的
